language: node_js
node_js:
  - node
addons:
  sonarcloud:
    organization: "react-security" # the key of the org you chose at step #3
    token:
      secure: "BG59d3Pu+riPig0Je9kjYePJuY5J999Hld5wAD3PWOuNtHUjMfmlhHNWitAPJI/1iuGZhJlkf7hs3XVwmL8USH9t5ILEktni2RGQfcsdZZnjwDgjOQIQcFpZiNABpqlFKrr/fvJdHsytvv7GzZfbX/7lDboRxcz4h6PZnRciRXLEPnjRjwJlPd9xEgu0ild/w1/JBGYTJUQZc6wHsCnjKEiIn8xiudblRIdCtNm5z2of6JKGGCWY117F9FPmjHUkiugZboL8uzpd8UliWlC4fQcXefbcJ7M8UABAt6lPzOM6TM9xdx7CMtSgqY2LaiNiL7F5USWa97g+dmLHmmtkH85HJBRG67YYP/3JNO6tDv0zs8cqhZxleKOtyuNAYqVMikzDCf5iwGF4gVBQ4DBxEMxFrOLKNBSN+6T6YJMd/Anc/kYfTEDqY32kkMJxtElRAwMha0Q4juQbJab/wTVKL7DsvnBwAw2nO0tDi30NmE+k61/z7slweCphSBaO3Pu0AamSUlS3BWmzI7t+XyBKgOA+aDM+F92X7AeoknA1JZVVD4WQ1cbp8CPBYGs/5NELzzKR7p6QAvJVIpmPVEdqNh2/z/kA805QgXdU99+LsJ5j4zb1ePy0xxzMXGK8SxKFuulgq+yRC+5YgHzVVrbllvbK0RAPQwsrEpI4WAjjWcs="
script:
  # other script steps might be done before running the actual analysis
  - yarn coverage
  - yarn report-coverage
  - sonar-scanner
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main

cache:
  directories:
    - node_modules
